# -*- coding: utf-8 -*-
"""m2Hybrid2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rYtnmz18DxAn7m_nzt6IleXSCF3Ehx37

Assignment
There are two parts to this assignment.

First, find one of the exercises you did in the book in pyCharm. Create a repository on Github for that exercise. Need help? Check out this link, https://help.github.com/en/articles/adding-an-existing-project-to-github-using-the-command-line (Links to an external site.)

Second, navigate to https://github.com/alancb/Intro-To-Programming (Links to an external site.). Here is a github repo with the first four units of the class. Your job is to submit a pull request in order to make the lessons better. Is there a grammar error somewhere that really bothers you? Perhaps you found a great video to add to an additional resources page. Clone the project, create a branch, commit your change, submit the pull request. Need help check out these links:

https://help.github.com/en/articles/cloning-a-repository (Links to an external site.)

https://github.com/Kunena/Kunena-Forum/wiki/Create-a-new-branch-with-git-and-manage-branches (Links to an external site.)

https://help.github.com/en/articles/creating-a-pull-request (Links to an external site.) (Links to an external site.)

Rubric
This assignment is based on completion. In canvas submit the link to your Github Repo, and the teacher will see your pull request.

ASSIGNMENT HYBRID 2 PART 1
"""

def main():
  v_farenheight = eval(input("What is the Farenheight temperature?"))
  celsius = (v_farenheight - 32)* (5 / 9)
  print(" The temperature is", celsius , "degrees Celsius.")
  
main()